Myblog/urls.py
from django.views.static import serve
from django.urls import path,include,re_path
import xadmin
# from rest_framework.authtoken.views import obtain_auth_token

from users.views import IndexView
from Myblog.settings import MEDIA_ROOT ,STATIC_ROOT
# from api.urls import router

urlpatterns = [
    path('api/',include('api.urls',namespace='apii')),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    path('cmdb/',include('cmdb.urls',namespace='cmdb')),

    path('xadmin/', xadmin.site.urls),
    # 富文本相关
    path('ueditor/', include('DjangoUeditor.urls')),

    path('', IndexView.as_view(),name='index'),

    path('user/', include('users.urls',namespace='user')),
    path('blog/', include('blogarticle.urls',namespace='blog')),
    path('resume/', include('resume.urls',namespace='resume')),

    re_path('media/(?P<path>.*)',serve,{'document_root': MEDIA_ROOT}),

    # 配置静态文件的访问处理函数
    re_path('static/(?P<path>.*)',serve,{'document_root':STATIC_ROOT}),

]


api/urls.py
# -*- coding:utf-8 -*- 
__author__ = 'SRP'

from django.urls import path,include
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

# from rest_framework.urlpatterns import format_suffix_patterns
# from rest_framework import renderers
# from rest_framework import routers

from .views import UserViewSet,ArticleViewSet,AssetView,asset

router = DefaultRouter()
router.register('users',UserViewSet)
router.register('articles',ArticleViewSet)

schema_view = get_schema_view(title='Pastebin API')  #添加一个模式

app_name = 'apii'

urlpatterns = [
    path('',include(router.urls)),
    path('schema/',schema_view),
    path('asset/',AssetView.as_view()),
    # path('asset1/',asset),
]



###################################################
# user_list = UserViewSet.as_view({
#     'get': 'list'
# })
# user_detail = UserViewSet.as_view({
#     'get': 'retrieve'
# })
# article_list = ArticleViewSet.as_view({
#     'get': 'list',
#     'post': 'create'
# })
# article_detail = ArticleViewSet.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
# })
#
# app_name = 'apii'
#
# # API endpoints
# urlpatterns = format_suffix_patterns([
#     path('',api_root),
#     path('users/', user_list.as_view(),name='user-list'),
#     path('user/<pk>', user_detail.as_view(),name='user-detail'),
#     path('articles/', article_list.as_view(),name='article-list'),
#     path('article/<pk>', article_detail.as_view(),name='article-detail'),
#
# ])






# from .views import UserView,ArticleView

# router = routers.DefaultRouter()
#
# router.register('users',UserView)
# router.register('articles',ArticleView)

apps/blogarticle/urls.py
# -*- coding:utf-8 -*- 
__author__ = 'SRP'
__date__ = '2018/5/4 17:23'

from django.urls import path

from .views import ArticleView,ArticleListView,ArticleAddView,ArticleModifyView,ArticleDelView
from .views import ArticleCommentAddView,ArticleCommentListView,ArticleCommentDelView,ReplyCommentView
from .views import AddCategoryView

app_name = 'blog'
urlpatterns = [

    path('article_detail/<article_id>', ArticleView.as_view(),name='article_detail'),
    path('article_list/', ArticleListView.as_view(),name='article_list'),
    path('article_add/', ArticleAddView.as_view(),name='article_add'),
    path('article_modify/<article_id>', ArticleModifyView.as_view(),name='article_modify'),
    path('article_del/<article_id>', ArticleDelView.as_view(),name='article_del'),
    path('article_comment/', ArticleCommentAddView.as_view(),name='article_comment_add'),
    path('article_comment_list/<article_id>', ArticleCommentListView.as_view(),name='article_comment_list'),
    path('article_comment_del/<comment_id>', ArticleCommentDelView.as_view(),name='article_comment_del'),
    path('article_reply_comment_add/', ReplyCommentView.as_view(),name='article_reply_comment_add'),
    path('article_category_add/', AddCategoryView.as_view(),name='article_category_add'),
  ]

apps/users/urls.py
# -*- coding:utf-8 -*- 
__author__ = 'SRP'
__date__ = '2018/5/4 17:23'

from django.urls import path

from .views import LoginView,LogoutView,RegisterView,UserListView
from .views import AddDelFavView,UserFavView,UserImageView,UserModifyPwdView,UserModifyEmailView,UserInfoView

app_name = 'user'
urlpatterns = [
    # path('get_article/', GetArticle.as_view(),name='get_article'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('user_list/',UserListView.as_view(),name='user_list'),
    path('add_fav/',AddDelFavView.as_view(),name='add_fav'),
    path('user_fav/',UserFavView.as_view(),name='user_fav'),
    path('user_img/',UserImageView.as_view(),name='user_img'),
    path('user_modify_pwd/',UserModifyPwdView.as_view(),name='user_modify_pwd'),
    path('user_modify_email/',UserModifyEmailView.as_view(),name='user_modify_email'),
    path('user_info/', UserInfoView.as_view(), name='user_info'),

]

cmdb/urls.py
# -*- coding:utf-8 -*- 
__author__ = 'SRP'

from django.urls import path

from cmdb import views

app_name = 'cmdb'

urlpatterns = [
    path('login/', views.LoginView.as_view(),name='login'),
    path('logout/', views.LogoutView.as_view(),name='logout'),
    path('', views.IndexView.as_view(),name='index'),
    path('cmdb/', views.CmdbView.as_view(),name='cmdb'),
    path('assets/', views.AssetListView.as_view(),name='assets_list'),
    path('asset/', views.AssetJsonView.as_view(),name='asset_json'),
    path('asset-<device_type_id>-<asset_nid>/', views.AssetDetailView.as_view(),name='asset_detail'),
    path('add-asset/', views.AddAssetView.as_view(),name='add_asset'),

    path('users/', views.UserListView.as_view(),name='users_list'),
    path('user/', views.UserJsonView.as_view(),name='user_json'),

    path('chart-<chart_type>/', views.ChartView.as_view(),name='chart'),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/__base__.html
<!DOCTYPE html>
{% load static %}

<html lang = "zh-CN">
<head>
    {% block meta %}<!-- block meta  -->{% endblock %}
    <meta charset="utf-8" />

    <title>{% block title %}  {% endblock %} - SRP-Blog</title>
    <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/uikit.gradient.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/sha1.min.js' %}"></script>
    <script src="{% static 'js/uikit.min.js' %}"></script>
    <script src="{% static 'js/sticky.min.js' %}"></script>
    <script src="{% static 'js/vue.min.js' %}"></script>
    <script src="{% static 'js/awesome.js' %}"></script>


    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'ueditor/ueditor.config.js' %}"></script>
{#    <script type="text/javascript" charset="utf-8" src="{% static 'ueditor/ueditor.all.min.js' %}"> </script>#}
    <script type="text/javascript" charset="utf-8" src="{% static 'ueditor/_examples/editor_api.js' %}"> </script>
    <script type="text/javascript" charset="utf-8" src="{% static 'ueditor/lang/zh-cn/zh-cn.js' %}"></script>

    {% block beforehead %}<!-- before head  -->{% endblock %}

</head>
<body>
    <nav class="uk-navbar uk-navbar-attached uk-margin-bottom">
        <div class="uk-container uk-container-center">
            <a href="/" class="uk-navbar-brand">SRP-Blog</a>
            <ul class="uk-navbar-nav">
                <li {% if request.path == '/' %}data-url="blogs"{% endif %}><a href="/"><i class="uk-icon-home"></i> 首页</a></li>
                <li {% if request.path|slice:'5' == '/blog' %}data-url="blogs"{% endif %}><a  href="{% url 'blog:article_list' %}"><i class="uk-icon-book"></i> 博文管理</a></li>
                <li {% if request.path|slice:'5' == '/user' %}data-url="blogs"{% endif %}><a href="{% url 'user:user_list' %}"><i class="uk-icon-book"></i> 用户管理</a></li>
{#                <li {% if request.path == '/blog/article_comment_list' %}data-url="blogs"{% endif %}><a  href="{% url 'blog:article_comment_list' 0 %}"><i class="uk-icon-book"></i> 评论管理</a></li>#}
                <li><a target="_blank" href="http://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000"><i class="uk-icon-book"></i> 教程</a></li>
                <li><a target="_blank" href="https://github.com/srp527/Mxonline362"><i class="uk-icon-github"></i> Git源码</a></li>
                <li><a target="_blank" href="http://srp.wangsir.wang"><i class="uk-icon-code"></i> 慕学在线网</a></li>
                <li><a target="_blank" href="http://127.0.0.1:8000/cmdb"><i class="uk-icon-code"></i> CMDB</a></li>
            </ul>
            <div class="uk-navbar-flip">
                <ul class="uk-navbar-nav">

                {% if request.user.is_authenticated %}

                    <li class="uk-parent" data-uk-dropdown>
                       <!-- <a href="#0"><i class="uk-icon-user"></i> {{ request.user.username }}({{ request.user.email }})</a> -->
                        <a href="#0"><img class="uk-border-circle" width="30" height="30" src="{{ MEDIA_URL }}{{ request.user.image }}">
                            {{ request.user.username }}({{ request.user.email }})</a>
                        <div class="uk-dropdown uk-dropdown-navbar">
                            <ul class="uk-nav uk-nav-navbar">
                                <li><a href="{% url 'user:logout' %}"><i class="uk-icon-sign-out"></i> 登出</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    <li><a href="{% url 'user:login' %}"><i class="uk-icon-sign-in"></i> 登陆</a></li>
                    <li><a href="{% url 'user:register' %}"><i class="uk-icon-edit"></i> 注册</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="uk-container uk-container-center">
        <div class="uk-grid">
            <!-- content -->
            {% block content %}

            {% endblock %}
            <!-- // content -->
        </div>
    </div>

    <div class="uk-margin-large-top" style="background-color:#eee; border-top:1px solid #ccc;">
        <div class="uk-container uk-container-center uk-text-center">
            <div class="uk-panel uk-margin-top uk-margin-bottom">
                <p>
                    <a target="_blank" href="http://weibo.com/liaoxuefeng" class="uk-icon-button uk-icon-weibo"></a>
                    <a target="_blank" href="https://github.com/michaelliao" class="uk-icon-button uk-icon-github"></a>
                    <a target="_blank" href="http://www.linkedin.com/in/liaoxuefeng" class="uk-icon-button uk-icon-linkedin-square"></a>
                    <a target="_blank" href="https://twitter.com/liaoxuefeng" class="uk-icon-button uk-icon-twitter"></a>
                </p>
                <p>Powered by <a href="http://awesome.liaoxuefeng.com">Awesome Python Webapp</a>. Copyright &copy; 2014. [<a href="/manage/" target="_blank">Manage</a>]</p>
                <p><a href="http://www.liaoxuefeng.com/" target="_blank">www.liaoxuefeng.com</a>. All rights reserved.</p>
                <a target="_blank" href="http://www.w3.org/TR/html5/"><i class="uk-icon-html5" style="font-size:64px; color: #444;"></i></a>
            </div>

        </div>
    </div>
</body>
</html>

templates/article_add.html
{% extends '__base__.html' %}

{% block title %}编写日志{% endblock %}

{% block beforehead %}



{% endblock %}

{% block content %}

    <div class="uk-width-1-1 uk-margin-bottom">
        <div class="uk-panel uk-panel-box">
            <ul class="uk-breadcrumb">
                <li><a href="{% url 'blog:article_comment_list' 0 %}">评论</a></li>
                <li><a href="{% url 'blog:article_list' %}">日志</a></li>
                <li><a href="{% url 'user:user_list' %}">用户</a></li>
            </ul>
        </div>
    </div>

    <div id="error" class="uk-width-1-1">
    </div>

       <div  class="uk-width-2-3">

        <form  id="jsForm" method="post" class="uk-form uk-form-stacked">
{#            <div class="uk-alert uk-alert-danger uk-hidden"></div>#}
            <tr class="uk-form-row">
                <td class="uk-form-label">文章类别:</td>
                <td align="left">
                    <select  id="category" >
                            <option  value="">==请选择==</option>
                        {% for category in all_categorys %}
                            <option value={{ category.id }}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" id="add_cate" placeholder="没有? 新建一个类型"><input onclick="add_category()" type="button" class="uk-button uk-button-primary" value="添加" >
                    <script>
                        function add_category() {
                            var category = $("#add_cate").val();
                            {#console.log('add_category',category);#}
                            if(category == ''){
                                alert('请输入一个类型名!');
                                return
                            }
                            $.ajax({
                                cache: false,
                                type: "POST",
                                url:"{% url 'blog:article_category_add' %}",
                                data:{'category':category},
                                // data: $("#jsForm").serialize(),
                                dataType: "json",
                                async: true,
                                beforeSend:function(xhr, settings){
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                                success: function(data) {
                                    if(data.status == 'fail'){
                                        if(data.msg == '添加失败'){
                                             return  alert(data.msg)
                                        }else{
                                           return  alert(data.msg)
                                        }

                                    }else if(data.status == 'success'){
                                        window.location.reload();//刷新当前页面.

                                    }
                                },
                            })
                        }
                    </script>
                </td>
            </tr>
            <hr>
            <div class="uk-form-row">
                <label class="uk-form-label">标题:</label>
                <div class="uk-form-controls">
                    <input id="js-title" name="title" type="text" placeholder="标题" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">摘要:</label>
                <div class="uk-form-controls">
                    <textarea  id="js-desc" rows="4" name="desc" placeholder="摘要" class="uk-width-1-1" style="resize:none;"></textarea>
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">内容:</label>
                <input type="hidden" id="answer" name="answer">
                     <span>
                    <script id="editor" type="text/plain" charset="utf-8" style="width:800px;height:500px;" >

                    </script></span>


{#                <div  class="uk-form-controls" >#}
{#                    <textarea id="js-content" rows="16" name="content" placeholder="内容" class="uk-width-1-1" style="resize:none;"></textarea>#}
{#                </div>#}
            </div>


            <div class="uk-form-row">
                <button id="js-pl-submit" onclick="add_art()" type="button" class="uk-button uk-button-primary"><i class="uk-icon-save"></i> 保存</button>
{#                <input onclick="add_art()" id="js-pl-submit" type="button"  value="保存" class="uk-button uk-button-primary">#}
                <a href="{% url 'blog:article_list' %}" class="uk-button"><i class="uk-icon-times"></i> 取消</a>
            </div>
            {% csrf_token %}
        </form>
    </div>

<script type="text/javascript">
        var ue = UE.getEditor('editor');
    //添加文章
    function add_art() {

        var category = $("#category").val();
        console.log('category:',category)
        if(category == ""){
            alert("请选择一个类别");
            return
        }

        var title = $("#js-title").val();
        if(title == ""){
             alert("标题不能为空");
            return
         }

        var desc = $("#js-desc").val();
         if(desc == ""){
            return  alert("摘要不能为空")
         }

        var content = UE.getEditor('editor').getContent();

        if(ue.hasContents() == false){
            return alert("内容不能为空")
         }

        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'blog:article_add' %}",
            data:{'title':title, 'desc':desc, 'content':content,'category':category},
            // data: $("#jsForm").serialize(),
            dataType: "json",
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="{% url 'user:login' %}";
                         return  alert(data.msg)
                    }else{
                       return  alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    // window.location.reload();//刷新当前页面.
                    // window.location.href="/blog/article_detail/ "+ data.art_id;
                        window.location.href="{% url 'blog:article_list' %} ";
                }
            },
        })
    }



</script>

{% endblock %}

{#    <script>#}
{#var#}
{#    ID = '{{ id }}',#}
{#    action = '{{ action }}';#}
{#function initVM(blog) {#}
{#    var vm = new Vue({#}
{#        el: '#vm',#}
{#        data: blog,#}
{#        methods: {#}
{#            submit: function (event) {#}
{#                event.preventDefault();#}
{#                var $form = $('#vm').find('form');#}
{#                $form.postJSON(action, this.$data, function (err, r) {#}
{#                    if (err) {#}
{#                        $form.showFormError(err);#}
{#                    }#}
{#                    else {#}
{#                        return location.assign('/manage/blogs');#}
{#                    }#}
{#                });#}
{#            }#}
{#        }#}
{#    });#}
{#    $('#vm').show();#}
{# }#}
{#$(function () {#}
{#    if (ID) {#}
{#        getJSON('/api/blogs/' + ID, function (err, blog) {#}
{#            if (err) {#}
{#                return fatal(err);#}
{#            }#}
{#            $('#loading').hide();#}
{#            initVM(blog);#}
{#        });#}
{#    }#}
{#    else {#}
{#        $('#loading').hide();#}
{#        initVM({#}
{#            name: '',#}
{#            summary: '',#}
{#            content: ''#}
{#        });#}
{#    }#}
{# });#}
{#</script>#}

{#<script>#}
{#var#}
{#    ID = '{{ id }}',#}
{#    action = '{{ action }}';#}
{#function initVM(blog) {#}
{#    var vm = new Vue({#}
{#        el: '#vm',#}
{#        data: blog,#}
{#        methods: {#}
{#            submit: function (event) {#}
{#                event.preventDefault();#}
{#                var $form = $('#vm').find('form');#}
{#                $form.postJSON(action, this.$data, function (err, r) {#}
{#                    if (err) {#}
{#                        $form.showFormError(err);#}
{#                    }#}
{#                    else {#}
{#                        return location.assign('/manage/blogs');#}
{#                    }#}
{#                });#}
{#            }#}
{#        }#}
{#    });#}
{#    $('#vm').show();#}
{# }#}
{#$(function () {#}
{#    if (ID) {#}
{#        getJSON('/api/blogs/' + ID, function (err, blog) {#}
{#            if (err) {#}
{#                return fatal(err);#}
{#            }#}
{#            $('#loading').hide();#}
{#            initVM(blog);#}
{#        });#}
{#    }#}
{#    else {#}
{#        $('#loading').hide();#}
{#        initVM({#}
{#            name: '',#}
{#            summary: '',#}
{#            content: ''#}
{#        });#}
{#    }#}
{# });#}
{#</script>#}